package Views;
import ControllerDAO.LoginController;
import Main.Main;
import Views.CadUsuario;
import Views.Menu;
import java.lang.ModuleLayer.Controller;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import java.sql.*;
import Connection.ConnectionFactory;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MANHICA
 */
public class Login extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    

    private final LoginController Controller;

  //  private final LoginController Controller;

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
       Controller = new LoginController(this);
       //conexao = ConnectionFactory.conector();
        System.out.println(conexao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblolho = new javax.swing.JLabel();
        lblApagarUsuario = new javax.swing.JLabel();
        lblocultar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pasSenha = new javax.swing.JPasswordField();
        btnsair = new javax.swing.JButton();
        check = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btnCriar = new javax.swing.JToggleButton();
        btnEntrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblolho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icon/outline_visibility_black_24dp.png"))); // NOI18N
        lblolho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblolhoMouseClicked(evt);
            }
        });
        getContentPane().add(lblolho, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 30, 40));

        lblApagarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApagarUsuario.setText("X");
        lblApagarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblApagarUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(lblApagarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 50, 40));

        lblocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icon/outline_visibility_off_black_24dp.png"))); // NOI18N
        lblocultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblocultarMouseClicked(evt);
            }
        });
        getContentPane().add(lblocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 30, 40));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 70, 40));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 90, 30));

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 270, 40));

        pasSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pasSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(pasSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 270, 40));

        btnsair.setText("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        getContentPane().add(btnsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 495, 100, 40));

        check.setText("Ver Senha");
        check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMouseClicked(evt);
            }
        });
        getContentPane().add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 100, -1));

        jLabel4.setText("Esqueceu senha?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 140, 30));

        btnCriar.setText("Criar conta");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        btnCriar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCriarKeyPressed(evt);
            }
        });
        getContentPane().add(btnCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 120, 40));

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        btnEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEntrarKeyPressed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/painel-login.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wallpaperflare.com_wallpaper (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            pasSenha.requestFocus();
        }

        if(evt.getKeyCode()==evt.VK_DOWN){
            pasSenha.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void pasSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pasSenhaKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            btnEntrar.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP){
            txtUsuario.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_DOWN){
            btnEntrar.requestFocus();
        }
    }//GEN-LAST:event_pasSenhaKeyPressed

    private void lblApagarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApagarUsuarioMouseClicked
        if(evt.getSource()==lblApagarUsuario){
            txtUsuario.setText("");
        }
    }//GEN-LAST:event_lblApagarUsuarioMouseClicked

    private void checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseClicked
        if (check.isSelected()){
            pasSenha.setEchoChar((char)0);
        } else{
            pasSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_checkMouseClicked

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        if (evt.getSource()==btnCriar){
            CadUsuario cad = new CadUsuario();
            cad.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnCriarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCriarKeyPressed
        if (evt.getKeyCode()==evt.VK_RIGHT){
            btnEntrar.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP){
            pasSenha.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_ENTER){
            CadUsuario cad = new CadUsuario();
            cad.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnCriarKeyPressed

    private void btnEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEntrarKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            CadUsuario cad = new CadUsuario();
            cad.setVisible(true);
            this.setVisible(false);
        }

        if (evt.getKeyCode()==evt.VK_LEFT){
            btnCriar.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP){
            pasSenha.requestFocus();
        }

    }//GEN-LAST:event_btnEntrarKeyPressed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
       if (evt.getSource()==btnEntrar){
          Controller.fizTarefa();
           Main menu = new Main();
           menu.setVisible(true);
           dispose();
       }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        if (evt.getSource()==btnsair){
            dispose();
        }
    }//GEN-LAST:event_btnsairActionPerformed

    private void lblolhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblolhoMouseClicked
        lblolho.setVisible(false);
        lblocultar.setVisible(true);
        pasSenha.setEchoChar((char)0);
    }//GEN-LAST:event_lblolhoMouseClicked

    private void lblocultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblocultarMouseClicked
        lblolho.setVisible(true);
        lblocultar.setVisible(false);
        pasSenha.setEchoChar('*');
    }//GEN-LAST:event_lblocultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       Login log = new Login();
       log.setVisible(true);
       
          
        
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCriar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnsair;
    private javax.swing.JCheckBox check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblApagarUsuario;
    private javax.swing.JLabel lblocultar;
    private javax.swing.JLabel lblolho;
    private javax.swing.JPasswordField pasSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String Mensagem) {
        JOptionPane.showMessageDialog(null, Mensagem);
    }

    public JPasswordField getPasSenha() {
        return pasSenha;
    }

    public void setPasSenha(JPasswordField pasSenha) {
        this.pasSenha = pasSenha;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }
    
    
    
}
