/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.JPanel;

/**
 *
 * @author MANHICA
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        painel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuDesktop = new javax.swing.JDesktopPane();
        lblMenu = new javax.swing.JLabel();
        painel = new javax.swing.JPanel();
        lblsair = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnEstatistica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblfechar = new javax.swing.JLabel();
        btnVenda = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 600));
        setSize(new java.awt.Dimension(1130, 900));

        menuDesktop.setBackground(new java.awt.Color(0, 51, 51));

        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icon/mais (2).png"))); // NOI18N
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });
        menuDesktop.add(lblMenu);
        lblMenu.setBounds(0, 0, 30, 30);

        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblsair.setForeground(new java.awt.Color(255, 255, 255));
        lblsair.setText("Terminar Sessao");
        lblsair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsairMouseClicked(evt);
            }
        });
        painel.add(lblsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, 40));

        jButton1.setText("Relatorio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 40));

        btnEstatistica.setText("Estatisticas");
        btnEstatistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticaActionPerformed(evt);
            }
        });
        painel.add(btnEstatistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/painel-login.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        painel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -30, 260, 530));

        menuDesktop.add(painel);
        painel.setBounds(0, 50, 190, 470);

        lblfechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icon/mais (2).png"))); // NOI18N
        lblfechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfecharMouseClicked(evt);
            }
        });
        menuDesktop.add(lblfechar);
        lblfechar.setBounds(0, 0, 30, 30);

        btnVenda.setText("Venda");
        btnVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVendaMouseClicked(evt);
            }
        });
        btnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaActionPerformed(evt);
            }
        });
        menuDesktop.add(btnVenda);
        btnVenda.setBounds(220, 100, 140, 70);

        jButton2.setText("Stock");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        menuDesktop.add(jButton2);
        jButton2.setBounds(460, 100, 150, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed

        MenuOrg  venda = new MenuOrg();
        venda.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnVendaActionPerformed

    private void btnVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaMouseClicked

    }//GEN-LAST:event_btnVendaMouseClicked

    private void lblfecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfecharMouseClicked
       
        if(evt.getSource()== lblfechar){
            
            painel.setVisible(false);
            lblfechar.setVisible(false);
            lblMenu.setVisible(true);
        }
    }//GEN-LAST:event_lblfecharMouseClicked

    private void lblsairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsairMouseClicked
        if (evt.getSource()==lblsair){
            Login log = new Login();
            log.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_lblsairMouseClicked

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        if(evt.getSource()== lblMenu){
            painel.setVisible(true);
            lblMenu.setVisible(false);
            lblfechar.setVisible(true);

        }
    }//GEN-LAST:event_lblMenuMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Stock stock = new Stock();
        stock.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEstatisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticaActionPerformed
         
    }//GEN-LAST:event_btnEstatisticaActionPerformed
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                
            }
            
        });
       
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstatistica;
    private javax.swing.JButton btnVenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblfechar;
    private javax.swing.JLabel lblsair;
    private javax.swing.JDesktopPane menuDesktop;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
