/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import ControllerDAO.ProdutosDAO;
import Modelo.CadastroProdutos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MANHICA
 */
public class Actualizacao extends javax.swing.JPanel {

    /**
     * Creates new form Actualizacao
     */
    public Actualizacao() {
        initComponents();
        preencherDadosFuncionario();
    }

     public void preencherDadosFuncionario() {
        ProdutosDAO pd = new ProdutosDAO();
        DefaultTableModel modelo = (DefaultTableModel) tabelaResultados.getModel();
        try {

            ArrayList<CadastroProdutos> produtos = pd.ListarTodos();
            modelo.setRowCount(0);
            produtos.forEach((CadastroProdutos cp) -> {
                modelo.addRow(new Object[]{
                   cp.getId(),cp.getNomeProduto(), cp.getMarca(), cp.getAnoFabrico(), cp.getReferenciaPeca(), cp.getModelo(), cp.getQuantidade(),
                    cp.getValorDeVenda(), cp.getValorDeCompra()});
                
            });

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaResultados = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        cbMarca = new javax.swing.JComboBox<>();
        cbModelo = new javax.swing.JComboBox<>();
        spAno = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        spValor = new javax.swing.JSpinner();
        txtValorVenda = new javax.swing.JTextField();
        ckValor = new javax.swing.JCheckBox();
        spQuantidade = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actualizacao");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 980, 50);

        tabelaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Marca de Carro", "Ano de Fabrico", "Referencia", "Modelo", "Quantidade", "Preco de Aquisicao", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaResultados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaResultadosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaResultados);

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 326, 980, 200);

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });
        add(txtNome);
        txtNome.setBounds(120, 80, 140, 30);

        cbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Mercedes", "BMW", "Nissan", "Ford", "Mazda", "Ranger Rover" }));
        cbMarca.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                cbMarcaCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        add(cbMarca);
        cbMarca.setBounds(120, 130, 140, 32);

        cbModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prado", "BT50", "D4D" }));
        add(cbModelo);
        cbModelo.setBounds(120, 190, 140, 31);

        spAno.setModel(new javax.swing.SpinnerNumberModel(2022, 1900, 2022, 4));
        spAno.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spAnoStateChanged(evt);
            }
        });
        add(spAno);
        spAno.setBounds(120, 260, 144, 31);

        jLabel2.setText("Nome");
        add(jLabel2);
        jLabel2.setBounds(10, 80, 60, 25);

        jLabel3.setText("Marca");
        add(jLabel3);
        jLabel3.setBounds(12, 137, 60, 25);

        jLabel4.setText("Ano de Fabrico");
        add(jLabel4);
        jLabel4.setBounds(12, 258, 80, 25);

        jLabel5.setText("Modelo");
        add(jLabel5);
        jLabel5.setBounds(10, 200, 60, 25);
        add(txtReferencia);
        txtReferencia.setBounds(800, 70, 150, 40);

        spValor.setModel(new javax.swing.SpinnerNumberModel(100.0d, 0.0d, null, 10.0d));
        spValor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spValorStateChanged(evt);
            }
        });
        add(spValor);
        spValor.setBounds(810, 130, 120, 40);

        txtValorVenda.setEditable(false);
        add(txtValorVenda);
        txtValorVenda.setBounds(820, 190, 120, 30);

        ckValor.setText("Digitar");
        ckValor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckValorStateChanged(evt);
            }
        });
        ckValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckValorMouseClicked(evt);
            }
        });
        add(ckValor);
        ckValor.setBounds(860, 220, 61, 25);

        spQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(spQuantidade);
        spQuantidade.setBounds(810, 270, 130, 30);

        jLabel6.setText("Ano de Fabrico");
        add(jLabel6);
        jLabel6.setBounds(12, 258, 80, 25);

        jLabel7.setText("Quantidade");
        add(jLabel7);
        jLabel7.setBounds(690, 270, 80, 25);

        jLabel8.setText("Valor de Venda");
        add(jLabel8);
        jLabel8.setBounds(690, 190, 90, 25);

        jLabel9.setText("Preco");
        add(jLabel9);
        jLabel9.setBounds(690, 130, 60, 40);

        jLabel10.setText("Referencia");
        add(jLabel10);
        jLabel10.setBounds(690, 70, 60, 25);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        add(btnActualizar);
        btnActualizar.setBounds(420, 190, 140, 40);
        add(jTextField1);
        jTextField1.setBounds(430, 90, 120, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Pesquisa");
        add(jLabel11);
        jLabel11.setBounds(340, 100, 58, 30);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        add(btnRemover);
        btnRemover.setBounds(420, 250, 140, 40);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        add(btnVoltar);
        btnVoltar.setBounds(10, 530, 63, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        if(evt.getKeyCode()== evt.VK_ENTER){
            cbMarca.requestFocus();
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void cbMarcaCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cbMarcaCaretPositionChanged
        if(cbMarca.getSelectedItem().equals("Toyota")){
            cbModelo.setVisible(true);
        }
    }//GEN-LAST:event_cbMarcaCaretPositionChanged

    private void spAnoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spAnoStateChanged

    }//GEN-LAST:event_spAnoStateChanged

    private void spValorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spValorStateChanged

        if(Float.parseFloat(spValor.getValue().toString()) > 0){
            float f = Float.parseFloat(spValor.getValue().toString());
            f+=f*0.3;
            txtValorVenda.setText(Float.toString(f));
        }
    }//GEN-LAST:event_spValorStateChanged

    private void ckValorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckValorStateChanged

    }//GEN-LAST:event_ckValorStateChanged

    private void ckValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckValorMouseClicked
        if (ckValor.isSelected()){
            txtValorVenda.setEditable(true);
        } else{
            txtValorVenda.setEditable(false);
        }
    }//GEN-LAST:event_ckValorMouseClicked

    private void tabelaResultadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaResultadosKeyReleased
        if(tabelaResultados.getSelectedRow() != -1){
            txtNome.setText(tabelaResultados.getValueAt(tabelaResultados.getSelectedRow(), 1).toString());
            txtReferencia.setText(tabelaResultados.getValueAt(tabelaResultados.getSelectedRow(), 4).toString());
            txtValorVenda.setText(tabelaResultados.getValueAt(tabelaResultados.getSelectedRow(), 8).toString());
            spAno.setValue(tabelaResultados.getValueAt(tabelaResultados.getSelectedRow(), 3).toString());
            spQuantidade.setValue(tabelaResultados.getValueAt(tabelaResultados.getSelectedRow(), 6).toString());
            spValor.setValue(tabelaResultados.getValueAt(tabelaResultados.getSelectedRow(), 7).toString());
            cbMarca.setSelectedItem(tabelaResultados.getValueAt(tabelaResultados.getSelectedRow(), 2).toString());
            cbModelo.setSelectedItem(tabelaResultados.getValueAt(tabelaResultados.getSelectedRow(), 5).toString());
            
            
        }
    }//GEN-LAST:event_tabelaResultadosKeyReleased

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (tabelaResultados.getSelectedRow() != -1){
            CadastroProdutos cad = new CadastroProdutos();
            ProdutosDAO dao = new ProdutosDAO();
            
             if(txtNome.getText().length() > 1){
                if(txtReferencia.getText().length() > 4){
                    if(Float.parseFloat(spValor.getValue().toString()) > 0){
                        if(Integer.parseInt(spQuantidade.getValue().toString()) > 0){
                            if(Integer.parseInt(spAno.getValue().toString()) < 2023){
                            
                            cad.setNomeProduto(txtNome.getText());
                           // cad.setValorDeCompra(Double.parseDouble(txtValor.getText()));
                            cad.setReferenciaPeca(txtReferencia.getText().toUpperCase());
                            cad.setValorDeVenda(Double.parseDouble(spValor.getValue().toString()));
                            cad.setAnoFabrico(Integer.parseInt(spAno.getValue().toString()));
                            cad.setQuantidade(Integer.parseInt(spQuantidade.getValue().toString()));
                            cad.setMarca(cbMarca.getSelectedItem().toString());
                            cad.setModelo(cbModelo.getSelectedItem().toString());
                            //cad.setId((int) tabelaResultados.getValueAt(tabelaResultados.getSelectedRow(), 0));
                            
                            dao.update(cad);
                            
                            }else{
                                JOptionPane.showMessageDialog(null, "Ano Invalido");
                            }
                        }else{
                            System.out.println("Quantidade Invalida");
                            JOptionPane.showMessageDialog(null, "Quantidade Invalido");
                        }
                    }else{
                        System.out.println("Valor invalido.");
                        JOptionPane.showMessageDialog(null, "Valor Invalido");
                    }
                }else{
                    System.out.println("Referencia Invalida");
                    JOptionPane.showMessageDialog(null, "Referencia Invalido");
                }
            }else{
                System.out.println("Nome vazio.");
                JOptionPane.showMessageDialog(null, "Nome do Produto Invalido");
            }
             
             
        
        
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
       if (tabelaResultados.getSelectedRow() != -1){
            CadastroProdutos cad = new CadastroProdutos();
            ProdutosDAO dao = new ProdutosDAO();
                cad.setId((int) tabelaResultados.getValueAt(tabelaResultados.getSelectedRow(), 0));
                dao.delete(cad);
        }
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if(evt.getSource()== btnVoltar){
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    
    public  void guardar(){
           
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JComboBox<String> cbModelo;
    private javax.swing.JCheckBox ckValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSpinner spAno;
    private javax.swing.JSpinner spQuantidade;
    private javax.swing.JSpinner spValor;
    private javax.swing.JTable tabelaResultados;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
