/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import ControllerDAO.ProdutosDAO;
import Modelo.CadastroProdutos;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MANHICA
 */
public class Armazem extends javax.swing.JPanel {

    /**
     * Creates new form Armazem
     */
    public Armazem() {
        initComponents();
        preencherDadosFuncionario();
    }
    
    
    public void preencherDadosFuncionario() {
        ProdutosDAO pd = new ProdutosDAO();
        DefaultTableModel modelo = (DefaultTableModel) tabelaResultados.getModel();
        try {

            ArrayList<CadastroProdutos> produtos = pd.ListarTodos();
            modelo.setRowCount(0);
            produtos.forEach((CadastroProdutos cp) -> {
                modelo.addRow(new Object[]{
                   cp.getId(),cp.getNomeProduto(), cp.getMarca(), cp.getAnoFabrico(), cp.getReferenciaPeca(), cp.getModelo(), cp.getQuantidade(),
                    cp.getValorDeVenda(), cp.getValorDeCompra()});
            });

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaResultados = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Marca de Carro", "Ano de Fabrico", "Referencia", "Modelo", "Quantidade", "Preco de Aquisicao", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaResultados);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 161, 1100, 260));

        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, 40));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 230, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Pesquisa");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 140, 30));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Armazem");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 489, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
                if(evt.getSource()== btnVoltar){
                     this.setVisible(false);
                }

    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabelaResultados;
    // End of variables declaration//GEN-END:variables
}
